### The external generator derives from GeneratorPythia8.
## The generator allows to run Pythia8 with POWHEG
#---> GeneratorPythia8POWHEG
[GeneratorExternal]
fileName=${O2DPG_MC_CONFIG_ROOT}/MC/config/PWGGAJE/external/generator/generator_pythia8_powheg.C
funcName=getGeneratorJEPythia8POWHEG("${O2DPG_MC_CONFIG_ROOT}/MC/config/MyTasks/external/powheg_W_mu.input", "/home/stephan/alice/O2DPG/MC/config/MyTasks/pythia8/pythia8_powheg.cfg", 1)

[GeneratorPythia8]
config=/home/stephan/alice/O2DPG/MC/config/MyTasks/pythia8/pythia8_powheg.cfg
includePartonEvent = true

[TriggerExternal]
fileName = ${O2DPG_MC_CONFIG_ROOT}/MC/config/MyTasks/trigger/trigger_W_mu.C
funcName = trigger_W_mu(-4.0,-2.5,10.0,100.0)